Revert "cbindgen: upgrade"
This reverts commit d019d02e2430e983fd0caa01c5a644b2ced19adf.

version 0.24.6 was yanked.
version 0.24.5 fails to build thunderbird:
thread 'main' panicked at '"Vector_(unnamed_enum_at_/construction/thunderbird/_build/dist/include/mozilla/Vector_h_457_3)"
is not a valid Ident',
/construction/thunderbird/thunderbird-102.12.0/third_party/rust/proc-macro2/src/fallback.rs:701:9